In [1]:
import pandas as pd
import numpy as np
import os 
import json

In [2]:
df = pd.read_csv("formattedData.csv")
df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1017,Point_1018,Point_1019,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,20.0,17.0,24.0,41.0,59.0,68.0,59.0,48.0,6.0,3.0
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,41.0,57.0,85.0,112.0,112.0,81.0,48.0,38.0,2.0,1.0
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,42.0,59.0,74.0,64.0,28.0,-2.0,-18.0,-9.0,3.0,5.0
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,72.0,69.0,61.0,68.0,72.0,72.0,74.0,82.0,2.0,1.0
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,35.0,20.0,21.0,39.0,53.0,44.0,29.0,26.0,6.0,3.0

In [3]:
subject_name = df["Folder"].unique()
subject_name

array(['Minh', 'Phuc', 'tuda_real', 'Vu'], dtype=object)

In [4]:
parent_folder = "Data"
folder_paths = [os.path.join(parent_folder, folder) for folder in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, folder))]
folder_paths.remove('Data/duc')

print(folder_paths)

['Data/Vu', 'Data/Minh', 'Data/tuda_real', 'Data/Phuc']

In [5]:
results = []

for folder in folder_paths:
    for filename in os.listdir(folder):
        if filename.endswith(".json"):
            file_path = os.path.join(folder, filename)
            print(file_path)
            # Đọc dữ liệu từ file txt và lưu vào list
            with open(file_path, 'r') as file:
                result = json.load(file)
                results.append(result)

Data/Vu/results.json
Data/Minh/results.json
Data/tuda_real/results.json
Data/Phuc/results.json

In [6]:
all_images = []
all_actions = []

for result in results:
    all_images.append([item['image'] for item in result])
    all_actions.append([item['action'] for item in result])

for image in all_images:
    print(len(image))

30
30
30
30

In [7]:
for name in subject_name:
    match name:
        case 'Vu': 
            df.loc[df['Folder'] == name,'Image'] = all_images[0]
            df.loc[df['Folder'] == name,'Action'] = all_actions[0]

        case 'Minh':
            df.loc[df['Folder'] == name,'Image'] = all_images[1]
            df.loc[df['Folder'] == name,'Action'] = all_actions[1]

        case 'tuda_real':
            df.loc[df['Folder'] == name,'Image'] = all_images[2]
            df.loc[df['Folder'] == name,'Action'] = all_actions[2]

        case 'Phuc':
            df.loc[df['Folder'] == name,'Image'] = all_images[3]
            df.loc[df['Folder'] == name,'Action'] = all_actions[3]

In [8]:
df.loc[df["Folder"] == "Phuc"]

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1019,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take,Image,Action
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,85.0,112.0,112.0,81.0,48.0,38.0,2.0,1.0,assets/image6.png,No
5,Phuc,2,77.0,72.0,70.0,77.0,87.0,82.0,70.0,72.0,...,-34.0,-5.0,6.0,-1.0,-22.0,-33.0,2.0,1.0,assets/image3.png,No
8,Phuc,3,102.0,49.0,16.0,37.0,68.0,41.0,-39.0,-104.0,...,189.0,156.0,102.0,76.0,80.0,80.0,2.0,1.0,assets/image4.png,No
12,Phuc,4,82.0,89.0,107.0,112.0,103.0,89.0,60.0,44.0,...,66.0,26.0,4.0,-7.0,-7.0,0.0,2.0,1.0,assets/image5.png,No
18,Phuc,5,52.0,57.0,44.0,27.0,25.0,49.0,82.0,87.0,...,39.0,21.0,35.0,55.0,51.0,24.0,2.0,1.0,assets/image2.png,No
22,Phuc,6,36.0,4.0,-3.0,10.0,37.0,58.0,75.0,73.0,...,24.0,18.0,12.0,21.0,42.0,64.0,2.0,1.0,assets/image1.png,Yes
26,Phuc,7,64.0,74.0,49.0,25.0,35.0,67.0,102.0,119.0,...,-33.0,-37.0,-33.0,-4.0,51.0,101.0,2.0,1.0,assets/image3.png,No
31,Phuc,8,60.0,61.0,70.0,91.0,97.0,76.0,70.0,65.0,...,85.0,83.0,70.0,40.0,18.0,9.0,2.0,1.0,assets/image6.png,No
34,Phuc,9,71.0,70.0,53.0,27.0,9.0,-5.0,-14.0,-25.0,...,41.0,58.0,71.0,69.0,67.0,77.0,2.0,1.0,assets/image4.png,No
36,Phuc,10,73.0,20.0,24.0,59.0,85.0,96.0,87.0,45.0,...,20.0,43.0,41.0,19.0,5.0,7.0,2.0,1.0,assets/image5.png,No
41,Phuc,11,19.0,25.0,27.0,36.0,56.0,71.0,65.0,64.0,...,52.0,70.0,70.0,45.0,32.0,48.0,2.0,1.0,assets/image2.png,No
45,Phuc,12,41.0,41.0,13.0,-13.0,1.0,21.0,9.0,-5.0,...,154.0,151.0,102.0,54.0,34.0,44.0,2.0,1.0,assets/image1.png,Yes
49,Phuc,13,-36.0,-13.0,7.0,-10.0,-50.0,-42.0,5.0,42.0,...,41.0,58.0,70.0,71.0,66.0,68.0,2.0,1.0,assets/image2.png,No
54,Phuc,14,-49.0,-60.0,-34.0,8.0,18.0,3.0,9.0,24.0,...,66.0,74.0,81.0,69.0,48.0,35.0,2.0,1.0,assets/image4.png,No
57,Phuc,15,67.0,44.0,29.0,4.0,-40.0,-58.0,-9.0,59.0,...,6.0,17.0,43.0,58.0,59.0,53.0,2.0,1.0,assets/image1.png,Yes
62,Phuc,16,88.0,101.0,73.0,57.0,77.0,98.0,97.0,76.0,...,-26.0,-38.0,-29.0,-13.0,2.0,19.0,2.0,1.0,assets/image3.png,No
65,Phuc,17,9.0,-1.0,11.0,23.0,33.0,60.0,96.0,104.0,...,27.0,-1.0,-23.0,-26.0,-22.0,-27.0,2.0,1.0,assets/image6.png,No
69,Phuc,18,27.0,17.0,7.0,2.0,-3.0,1.0,18.0,37.0,...,39.0,40.0,50.0,74.0,77.0,48.0,2.0,1.0,assets/image4.png,No
73,Phuc,19,5.0,-8.0,-1.0,12.0,21.0,22.0,19.0,32.0,...,51.0,39.0,53.0,67.0,74.0,86.0,2.0,1.0,assets/image1.png,Yes
78,Phuc,20,44.0,39.0,11.0,-12.0,3.0,57.0,96.0,88.0,...,27.0,41.0,84.0,118.0,125.0,103.0,2.0,1.0,assets/image5.png,No
82,Phuc,21,3.0,-3.0,12.0,20.0,12.0,17.0,43.0,67.0,...,-91.0,-126.0,-102.0,-40.0,-6.0,-2.0,2.0,1.0,assets/image1.png,Yes
87,Phuc,22,103.0,90.0,80.0,67.0,42.0,6.0,2.0,39.0,...,4.0,28.0,27.0,9.0,28.0,80.0,2.0,1.0,assets/image2.png,No
88,Phuc,23,91.0,105.0,121.0,129.0,147.0,169.0,161.0,122.0,...,58.0,80.0,80.0,52.0,36.0,32.0,2.0,1.0,assets/image6.png,No
92,Phuc,24,-132.0,-66.0,-13.0,16.0,40.0,91.0,139.0,133.0,...,-9.0,-67.0,-101.0,-93.0,-78.0,-71.0,2.0,1.0,assets/image3.png,No
96,Phuc,25,-33.0,-104.0,-114.0,-50.0,28.0,33.0,0.0,3.0,...,19.0,45.0,87.0,121.0,120.0,76.0,2.0,1.0,assets/image6.png,No
102,Phuc,26,51.0,58.0,57.0,42.0,20.0,6.0,16.0,16.0,...,-44.0,21.0,86.0,117.0,93.0,36.0,2.0,1.0,assets/image5.png,No
105,Phuc,27,58.0,-11.0,-50.0,-27.0,26.0,68.0,38.0,-13.0,...,97.0,52.0,37.0,55.0,84.0,99.0,2.0,1.0,assets/image5.png,No
109,Phuc,28,-49.0,-88.0,-81.0,-4.0,88.0,128.0,92.0,23.0,...,53.0,52.0,85.0,113.0,99.0,55.0,2.0,1.0,assets/image3.png,No
112,Phuc,29,27.0,5.0,-3.0,3.0,-7.0,-6.0,43.0,106.0,...,23.0,33.0,27.0,-1.0,-53.0,-86.0,2.0,1.0,assets/image2.png,No
119,Phuc,30,296.0,309.0,320.0,338.0,353.0,345.0,326.0,292.0,...,70.0,57.0,36.0,24.0,9.0,10.0,2.0,1.0,assets/image4.png,No

In [9]:
df['Image'] = df['Image'].str.extract(r'(\d+)').astype(float)
df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1019,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take,Image,Action
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,24.0,41.0,59.0,68.0,59.0,48.0,6.0,3.0,5.0,No
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,85.0,112.0,112.0,81.0,48.0,38.0,2.0,1.0,6.0,No
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,74.0,64.0,28.0,-2.0,-18.0,-9.0,3.0,5.0,2.0,No
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,61.0,68.0,72.0,72.0,74.0,82.0,2.0,1.0,2.0,No
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,21.0,39.0,53.0,44.0,29.0,26.0,6.0,3.0,1.0,No

In [10]:
df['P300'] = df.apply(lambda row: 'Yes' if row['Image'] == row['Take'] or row['Image'] == row['Not take'] else 'No', axis=1)
df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take,Image,Action,P300
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,41.0,59.0,68.0,59.0,48.0,6.0,3.0,5.0,No,No
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,112.0,112.0,81.0,48.0,38.0,2.0,1.0,6.0,No,No
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,64.0,28.0,-2.0,-18.0,-9.0,3.0,5.0,2.0,No,No
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,68.0,72.0,72.0,74.0,82.0,2.0,1.0,2.0,No,Yes
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,39.0,53.0,44.0,29.0,26.0,6.0,3.0,1.0,No,No

In [11]:
mapping = {"Yes": 1, "No": 0}
df['Action'] = df['Action'].map(mapping)
df['P300'] = df['P300'].map(mapping)

df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take,Image,Action,P300
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,41.0,59.0,68.0,59.0,48.0,6.0,3.0,5.0,0,0
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,112.0,112.0,81.0,48.0,38.0,2.0,1.0,6.0,0,0
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,64.0,28.0,-2.0,-18.0,-9.0,3.0,5.0,2.0,0,0
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,68.0,72.0,72.0,74.0,82.0,2.0,1.0,2.0,0,1
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,39.0,53.0,44.0,29.0,26.0,6.0,3.0,1.0,0,0

In [12]:
df['Deception'] = df['Action'] ^ df['P300']
df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take,Image,Action,P300,Deception
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,59.0,68.0,59.0,48.0,6.0,3.0,5.0,0,0,0
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,112.0,81.0,48.0,38.0,2.0,1.0,6.0,0,0,0
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,28.0,-2.0,-18.0,-9.0,3.0,5.0,2.0,0,0,0
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,72.0,72.0,74.0,82.0,2.0,1.0,2.0,0,1,1
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,53.0,44.0,29.0,26.0,6.0,3.0,1.0,0,0,0

In [13]:
deception_mapping = {0: "Truth", 1: "Lie"}
df['Deception'] = df['Deception'].map(deception_mapping)
df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take,Image,Action,P300,Deception
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,59.0,68.0,59.0,48.0,6.0,3.0,5.0,0,0,Truth
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,112.0,81.0,48.0,38.0,2.0,1.0,6.0,0,0,Truth
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,28.0,-2.0,-18.0,-9.0,3.0,5.0,2.0,0,0,Truth
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,72.0,72.0,74.0,82.0,2.0,1.0,2.0,0,1,Lie
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,53.0,44.0,29.0,26.0,6.0,3.0,1.0,0,0,Truth

In [14]:
df.to_csv("finalData.csv", index = False)