In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("rawData.csv")
df['Filename'] = df['Filename'].str.extract(r'(\d+)').astype(int)
df = df.sort_values(by='Filename').reset_index(drop=True)
df.head()

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1015,Point_1016,Point_1017,Point_1018,Point_1019,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,36.0,27.0,20.0,17.0,24.0,41.0,59.0,68.0,59.0,48.0
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,71.0,54.0,41.0,57.0,85.0,112.0,112.0,81.0,48.0,38.0
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,44.0,43.0,42.0,59.0,74.0,64.0,28.0,-2.0,-18.0,-9.0
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,67.0,70.0,72.0,69.0,61.0,68.0,72.0,72.0,74.0,82.0
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,50.0,48.0,35.0,20.0,21.0,39.0,53.0,44.0,29.0,26.0

In [8]:
subject_name = df["Folder"].unique()
subject_name

array(['Minh', 'Phuc', 'tuda_real', 'Vu'], dtype=object)

In [9]:
for name in subject_name:
    match name:
        case 'Vu': 
            df.loc[df['Folder'] == name,'Take'] = 2
            df.loc[df['Folder'] == name,'Not take'] = 1

        case 'Minh':
            df.loc[df['Folder'] == name,'Take'] = 6
            df.loc[df['Folder'] == name,'Not take'] = 3

        case 'tuda_real':
            df.loc[df['Folder'] == name,'Take'] = 3
            df.loc[df['Folder'] == name,'Not take'] = 5

        case 'Phuc':
            df.loc[df['Folder'] == name,'Take'] = 2
            df.loc[df['Folder'] == name,'Not take'] = 1

df.head(10)

,Folder,Filename,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_1017,Point_1018,Point_1019,Point_1020,Point_1021,Point_1022,Point_1023,Point_1024,Take,Not take
0,Minh,1,32.0,12.0,-3.0,-11.0,-10.0,8.0,26.0,35.0,...,20.0,17.0,24.0,41.0,59.0,68.0,59.0,48.0,6.0,3.0
1,Phuc,1,13.0,50.0,64.0,48.0,27.0,41.0,87.0,104.0,...,41.0,57.0,85.0,112.0,112.0,81.0,48.0,38.0,2.0,1.0
2,tuda_real,1,60.0,57.0,52.0,58.0,81.0,93.0,86.0,64.0,...,42.0,59.0,74.0,64.0,28.0,-2.0,-18.0,-9.0,3.0,5.0
3,Vu,1,67.0,75.0,88.0,90.0,87.0,90.0,81.0,40.0,...,72.0,69.0,61.0,68.0,72.0,72.0,74.0,82.0,2.0,1.0
4,Minh,2,100.0,97.0,89.0,86.0,90.0,102.0,100.0,89.0,...,35.0,20.0,21.0,39.0,53.0,44.0,29.0,26.0,6.0,3.0
5,Phuc,2,77.0,72.0,70.0,77.0,87.0,82.0,70.0,72.0,...,-69.0,-61.0,-34.0,-5.0,6.0,-1.0,-22.0,-33.0,2.0,1.0
6,tuda_real,2,88.0,80.0,76.0,74.0,54.0,50.0,64.0,69.0,...,86.0,72.0,49.0,44.0,48.0,49.0,60.0,86.0,3.0,5.0
7,Vu,2,85.0,85.0,91.0,97.0,101.0,117.0,122.0,120.0,...,-9.0,-4.0,-2.0,2.0,8.0,10.0,9.0,18.0,2.0,1.0
8,Phuc,3,102.0,49.0,16.0,37.0,68.0,41.0,-39.0,-104.0,...,180.0,193.0,189.0,156.0,102.0,76.0,80.0,80.0,2.0,1.0
9,Minh,3,53.0,55.0,51.0,48.0,48.0,42.0,39.0,38.0,...,66.0,87.0,77.0,51.0,40.0,66.0,112.0,140.0,6.0,3.0

In [10]:
df.to_csv("formattedData.csv", index = False)